version: 2.1

jobs:
  minecraft_server:
    docker:
      - image: docker:18.09.6
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build --platform linux/amd64,linux/arm64,linux/arm/v7 -t itzg/minecraft-server:multiarch .

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server:
          filters:
            branches:
              ignore:
                - armv7
                - multiarch
